spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather_spring_db
    username: root
    password: jakubowy22
  jpa:
    hibernate:
      dll-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

#spring.datasource.url=jdbc:mysql://localhost:3306/weather_spring_db
#spring.datasource.username=root
#spring.datasource.password=jakubowy22
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQDialect